##📌 EXTRACCIÓN

In [137]:
import pandas as pd

In [138]:
datos = pd.read_csv('/content/datos_limpios.csv')
datos

,id,evasión,genero,tiene_+60,tiene_pareja,tiene_dependientes,tiempo_contrato_meses,servicio_telefono,multiples_lineas,tipo_internet,...,proteccion_dispositivo,soporte_tecnico,streaming_TV,streaming_peliculas,tipo_contrato,factura_digital,metodo_pago,facturacion_mensual,facturacion_total,facturacion_diaria
0,0002-ORFBO,No,Femenino,No,Sí,Sí,9,Sí,No,DSL,...,No,Sí,Sí,No,Anual,Sí,Cheque enviado por correo,65.60,593.30,2.186667
1,0003-MKNFE,No,Masculino,No,No,No,9,Sí,Sí,DSL,...,No,No,No,Sí,Mensual,No,Cheque enviado por correo,59.90,542.40,1.996667
2,0004-TLHLJ,Sí,Masculino,No,No,No,4,Sí,No,Fiber optic,...,Sí,No,No,No,Mensual,Sí,Cheque electrónico,73.90,280.85,2.463333
3,0011-IGKFF,Sí,Masculino,Sí,Sí,No,13,Sí,No,Fiber optic,...,Sí,No,Sí,Sí,Mensual,Sí,Cheque electrónico,98.00,1237.85,3.266667
4,0013-EXCHZ,Sí,Femenino,Sí,Sí,No,3,Sí,No,Fiber optic,...,No,Sí,Sí,No,Mensual,Sí,Cheque enviado por correo,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,9987-LUTYD,No,Femenino,No,No,No,13,Sí,No,DSL,...,No,Sí,No,No,Anual,No,Cheque enviado por correo,55.15,742.90,1.838333
7028,9992-RRAMN,Sí,Masculino,No,Sí,No,22,Sí,Sí,Fiber optic,...,No,No,No,Sí,Mensual,Sí,Cheque electrónico,85.10,1873.70,2.836667
7029,9992-UJOEL,No,Masculino,No,No,No,2,Sí,No,DSL,...,No,No,No,No,Mensual,Sí,Cheque enviado por correo,50.30,92.75,1.676667
7030,9993-LHIEB,No,Masculino,No,Sí,Sí,67,Sí,No,DSL,...,Sí,Sí,No,Sí,Bienal,No,Cheque enviado por correo,67.85,4627.65,2.261667
7031,9995-HOTOH,No,Masculino,No,Sí,Sí,63,No,Sin servicio de teléfono,DSL,...,Sí,No,Sí,Sí,Bienal,No,Cheque electrónico,59.00,3707.60,1.966667

In [139]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      7032 non-null   object
 1   evasión                 7032 non-null   object
 2   genero                  7032 non-null   object
 3   tiene_+60               7032 non-null   object
 4   tiene_pareja            7032 non-null   object
 5   tiene_dependientes      7032 non-null   object
 6   tiempo_contrato_meses   7032 non-null   int64
 7   servicio_telefono       7032 non-null   object
 8   multiples_lineas        7032 non-null   object
 9   tipo_internet           7032 non-null   object
 10  seguridad_online        7032 non-null   object
 11  backup_online           7032 non-null   object
 12  proteccion_dispositivo  7032 non-null   object
 13  soporte_tecnico         7032 non-null   object
 14  streaming_TV            7032 non-null   object
 15  streaming_peliculas     7032 non-null   object
 16  tipo_contrato           7032 non-null   object
 17  factura_digital         7032 non-null   object
 18  metodo_pago             7032 non-null   object
 19  facturacion_mensual     7032 non-null   float64
 20  facturacion_total       7032 non-null   float64
 21  facturacion_diaria      7032 non-null   float64
dtypes: float64(3), int64(1), object(18)
memory usage: 1.2+ MB

In [140]:
datos.describe()

,tiempo_contrato_meses,facturacion_mensual,facturacion_total,facturacion_diaria
count,7032.000000,7032.000000,7032.000000,7032.000000
mean,32.421786,64.798208,2283.300441,2.159940
std,24.545260,30.085974,2266.771362,1.002866
min,1.000000,18.250000,18.800000,0.608333
25%,9.000000,35.587500,401.450000,1.186250
50%,29.000000,70.350000,1397.475000,2.345000
75%,55.000000,89.862500,3794.737500,2.995417
max,72.000000,118.750000,8684.800000,3.958333

In [141]:
datos.describe(include='O')

,id,evasión,genero,tiene_+60,tiene_pareja,tiene_dependientes,servicio_telefono,multiples_lineas,tipo_internet,seguridad_online,backup_online,proteccion_dispositivo,soporte_tecnico,streaming_TV,streaming_peliculas,tipo_contrato,factura_digital,metodo_pago
count,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032
unique,7032,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4
top,9995-HOTOH,No,Masculino,No,No,No,Sí,No,Fiber optic,No,No,No,No,No,No,Mensual,Sí,Cheque electrónico
freq,1,5163,3549,5890,3639,4933,6352,3385,3096,3497,3087,3094,3472,2809,2781,3875,4168,2365

In [142]:
for col in datos.columns:
    print(col)
    print(datos[col].unique())
    print('-'*50)

id
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
--------------------------------------------------
evasión
['No' 'Sí']
--------------------------------------------------
genero
['Femenino' 'Masculino']
--------------------------------------------------
tiene_+60
['No' 'Sí']
--------------------------------------------------
tiene_pareja
['Sí' 'No']
--------------------------------------------------
tiene_dependientes
['Sí' 'No']
--------------------------------------------------
tiempo_contrato_meses
[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 37 49 66 67
 20 43 59 12 27  2 25 29 14 35 64 39 40 11  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 31 36 17 18 51 38 42]
--------------------------------------------------
servicio_telefono
['Sí' 'No']
--------------------------------------------------
multiples_lineas
['No' 'Sí' 'Sin servicio de teléfono']
--------------------------------------------------
tipo_internet
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
seguridad_online
['No' 'Sí' 'Sin servicio de internet']
--------------------------------------------------
backup_online
['Sí' 'No' 'Sin servicio de internet']
--------------------------------------------------
proteccion_dispositivo
['No' 'Sí' 'Sin servicio de internet']
--------------------------------------------------
soporte_tecnico
['Sí' 'No' 'Sin servicio de internet']
--------------------------------------------------
streaming_TV
['Sí' 'No' 'Sin servicio de internet']
--------------------------------------------------
streaming_peliculas
['No' 'Sí' 'Sin servicio de internet']
--------------------------------------------------
tipo_contrato
['Anual' 'Mensual' 'Bienal']
--------------------------------------------------
factura_digital
['Sí' 'No']
--------------------------------------------------
metodo_pago
['Cheque enviado por correo' 'Cheque electrónico'
 'Tarjeta de crédito (automático)' 'Transferencia bancaria (automático)']
--------------------------------------------------
facturacion_mensual
[65.6  59.9  73.9  ... 91.75 68.8  67.85]
--------------------------------------------------
facturacion_total
[ 593.3   542.4   280.85 ...  742.9  4627.65 3707.6 ]
--------------------------------------------------
facturacion_diaria
[2.18666667 1.99666667 2.46333333 ... 3.05833333 2.29333333 2.26166667]
--------------------------------------------------

##🛠️ Pre procesamiento

In [143]:
datos = datos.drop(columns=['id'])
datos.head(2)

,evasión,genero,tiene_+60,tiene_pareja,tiene_dependientes,tiempo_contrato_meses,servicio_telefono,multiples_lineas,tipo_internet,seguridad_online,...,proteccion_dispositivo,soporte_tecnico,streaming_TV,streaming_peliculas,tipo_contrato,factura_digital,metodo_pago,facturacion_mensual,facturacion_total,facturacion_diaria
0,No,Femenino,No,Sí,Sí,9,Sí,No,DSL,No,...,No,Sí,Sí,No,Anual,Sí,Cheque enviado por correo,65.6,593.3,2.186667
1,No,Masculino,No,No,No,9,Sí,Sí,DSL,No,...,No,No,No,Sí,Mensual,No,Cheque enviado por correo,59.9,542.4,1.996667

In [144]:
datos = datos.replace({'Sin servicio de teléfono': 'No', 'Sin servicio de internet': 'No'})

In [145]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [146]:
columnas = datos.columns

In [147]:
categoricas = ['evasión', 'genero', 'tiene_+60', 'tiene_pareja', 'tiene_dependientes','servicio_telefono',
               'multiples_lineas', 'tipo_internet', 'seguridad_online', 'backup_online', 'proteccion_dispositivo',
               'soporte_tecnico', 'streaming_TV', 'streaming_peliculas', 'tipo_contrato', 'factura_digital', 'metodo_pago']

In [148]:
one_hot_encoding = make_column_transformer((OneHotEncoder(drop='if_binary'), categoricas), remainder = 'passthrough', sparse_threshold=0)

In [149]:
datos = one_hot_encoding.fit_transform(datos)

In [150]:
one_hot_encoding.get_feature_names_out(columnas)

array(['onehotencoder__evasión_Sí', 'onehotencoder__genero_Masculino',
       'onehotencoder__tiene_+60_Sí', 'onehotencoder__tiene_pareja_Sí',
       'onehotencoder__tiene_dependientes_Sí',
       'onehotencoder__servicio_telefono_Sí',
       'onehotencoder__multiples_lineas_Sí',
       'onehotencoder__tipo_internet_DSL',
       'onehotencoder__tipo_internet_Fiber optic',
       'onehotencoder__tipo_internet_No',
       'onehotencoder__seguridad_online_Sí',
       'onehotencoder__backup_online_Sí',
       'onehotencoder__proteccion_dispositivo_Sí',
       'onehotencoder__soporte_tecnico_Sí',
       'onehotencoder__streaming_TV_Sí',
       'onehotencoder__streaming_peliculas_Sí',
       'onehotencoder__tipo_contrato_Anual',
       'onehotencoder__tipo_contrato_Bienal',
       'onehotencoder__tipo_contrato_Mensual',
       'onehotencoder__factura_digital_Sí',
       'onehotencoder__metodo_pago_Cheque electrónico',
       'onehotencoder__metodo_pago_Cheque enviado por correo',
       'onehotencoder__metodo_pago_Tarjeta de crédito (automático)',
       'onehotencoder__metodo_pago_Transferencia bancaria (automático)',
       'remainder__tiempo_contrato_meses',
       'remainder__facturacion_mensual', 'remainder__facturacion_total',
       'remainder__facturacion_diaria'], dtype=object)

In [152]:
datos_codificados = pd.DataFrame(datos, columns=one_hot_encoding.get_feature_names_out(columnas))
datos_codificados

,onehotencoder__evasión_Sí,onehotencoder__genero_Masculino,onehotencoder__tiene_+60_Sí,onehotencoder__tiene_pareja_Sí,onehotencoder__tiene_dependientes_Sí,onehotencoder__servicio_telefono_Sí,onehotencoder__multiples_lineas_Sí,onehotencoder__tipo_internet_DSL,onehotencoder__tipo_internet_Fiber optic,onehotencoder__tipo_internet_No,...,onehotencoder__tipo_contrato_Mensual,onehotencoder__factura_digital_Sí,onehotencoder__metodo_pago_Cheque electrónico,onehotencoder__metodo_pago_Cheque enviado por correo,onehotencoder__metodo_pago_Tarjeta de crédito (automático),onehotencoder__metodo_pago_Transferencia bancaria (automático),remainder__tiempo_contrato_meses,remainder__facturacion_mensual,remainder__facturacion_total,remainder__facturacion_diaria
0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,9.0,65.60,593.30,2.186667
1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,9.0,59.90,542.40,1.996667
2,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,4.0,73.90,280.85,2.463333
3,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,13.0,98.00,1237.85,3.266667
4,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,3.0,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,13.0,55.15,742.90,1.838333
7028,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,22.0,85.10,1873.70,2.836667
7029,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,2.0,50.30,92.75,1.676667
7030,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,67.0,67.85,4627.65,2.261667
7031,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,63.0,59.00,3707.60,1.966667